#=
Samuel Nasman (BYU FLOW Lab)
Optimizing a wing to minimize induced drag
17 July 2024
=#

using VortexLattice, SNOW, Plots, LaTeXStrings
include("wing_constants.jl")
include("VLM_functions.jl")


"""
    load_optim_params(c_i, ns)

Given an initial chord distribution and the number of span-wise panels, return x0, ng, lx, ux, lg, ug, and options.

# Arguments
- `c_i::Float64`: 
- `ns::Int`: Number of spanwise panels.
- `nc::Int`: Number of chord-wise panels.
- `CDiff_run::Bool`: Whether to calculate the coefficient of induced drag in the far-field

# Returns
- `x0::Vector`: Initial chord distribution to be fed to SNOW.jl
- `ng::Int`: Number of constraints to feed SNOW.jl
- `lx::Vector`: Lower bounds on x.
- `ux::Vector`: Upper bounds on x.
- `lg::Vector`: Lower bounds on g.
- `ug::Vector`: Upper bounds on g.
- `options::Options`: Struct of optional parameters to feed SNOW.jl

# Example
```jldoctest
julia> load_optim_params(1.0, 3)
([1.0, 1.0, 1.0, 1.0], 4, [1.0e-5, 1.0e-5, 1.0e-5, 1.0e-5], [Inf, Inf, Inf, Inf], [1.7, -Inf, -Inf, -Inf], [Inf, -1.0e-6, -1.0e-6, -1.0e-6], Options{DensePattern, ForwardFD, IPOPT{Dict{String, Int64}}}(DensePattern(), ForwardFD(), IPOPT{Dict{String, Int64}}(Dict("max_iter" => 3000))))
```
"""
function load_optim_params(c_i::Float64, ns::Int)
    ng = ns+1  # number of constraints (g)
    x0 = c_i * ones(ns+1) # initial chord distribution
    lx = 0.00001 * ones(ns+1) # lower bounds on chord distribution (non-zero to avoid potential errors)
    ux = Inf * ones(ns+1) # upper bounds on chord distribution
    lg = vcat(1.7, -Inf*ones(ns))  # lower bounds on g (1.7 N is the minimum Lift)
    ug = vcat(Inf, -0.000001*ones(ns)) # upper bounds on g (negative non-zero upper bound to enforce a monotonically decreasing chord distribution)

    ip_options = Dict(
        "max_iter" => 3000, # define optional parameters for IPOPT
        #"output_file" => "images/$output_filename.out" 
    )
    options = Options(solver=IPOPT(ip_options))  # choosing IPOPT solver and preparing IPOPT options to load into SNOW

    return x0, ng, lx, ux, lg, ug, options
end


"""
    run_chord_optim(ns, nc, c_i, output_filename)

Given the number of span-wise and chord-wise panels, an initial length for a uniform chord distribution, and a filename for saving to VTK files, optimize
the chord distribution using SNOW.jl to minimize drag and write the result to VTK files. Additionally, print the optimized chord distribution (xstar), 
minimized induced drag (fstar), whether the optimization succeeded (info), and the lift generated by the optimized wing (lift). 

# Arguments 
- `ns::Int`: Number of spanwise panels.
- `nc::Int`: Number of chord-wise panels.
- `c_i::Float64`:
- `output_filename::String`: 

# Example
```jldoctest
julia> run_chord_optim(4, 6, 1.0, "test")
...
xstar = [1.158953937269707, 1.1589494398673357, 1.0321804324508204, 0.8813544247245128, 0.5191080277239004]
fstar = 0.02561881380995737
info = Solve_Succeeded
Lift = 1.6999999834025452
write_vtk successful.
```
"""
function run_chord_optim(ns::Int, nc::Int, c_i::Float64, output_filename::String)

    # define the optimization problem:
    function min_C_D!(g, x)
        # run VLM to collect information for definitions of f(x) and g(x)
        CL, CDiff, Sref = run_VLM(x, ns, nc, true) # run VortexLattice.jl's steady_analysis() and return the lift and far field induced drag coefficients and reference area
        
        # objective function
        f = force(CDiff, Sref, Vinf) # from the CDiff and Sref, calculate the dimensionalized induced drag
    
        # constraints
        g[1] = force(CL, Sref, Vinf) # from CL, calculate the dimensionalized lift
        g[2:(ns+1)] = diff(x) # difference between consecutive chord values, used to enforce monotonicity constraint 
    
        return f
    end

    x0, ng, lx, ux, lg, ug, options = load_optim_params(c_i, ns) # load constraints, IPOPT options, and other necessary optimization parameters

    xopt, fopt, info = minimize(min_C_D!, x0, ng, lx, ux, lg, ug, options)  # perform optimization
        println("xstar = ", xopt) # print optimized chord distribution
        println("fstar = ", fopt) # print minimized induced drag
        println("info = ", info) # print whether optimization solve succeeded

        CL, CDiff, Sref, surfaces, circulation, circ_y_coor, ideal_circ, ideal_circ_range, error = run_VLM(xopt, ns, nc, false) # run VLM using optimized chord distribution
    L = force(CL, Sref, Vinf)
    sd, min_err, max_err, min_perc_err, max_perc_err = error
        println("lift = ", L) # print the lift generated by the optimized wing
        println("sd = ", sd)
        println("min error = ", min_err)
        println("max error = ", max_err)
        println("min percent error = ", min_perc_err)
        println("max percent error = ", max_perc_err)
    write_vtk("vtk/$output_filename", surfaces; symmetric) # generate VTK files for visualization
        println("write_vtk successful.")

    plot(circ_y_coor, circulation, label="Optimized", ylabel="\$\\textrm{Circulation (m}^2 \\textrm{ / s)}\$", xlabel="\$\\textrm{y-position (m)}\$")
    plot!(ideal_circ_range, ideal_circ, label="Elliptic")
    rm("images/$output_filename.png", force=true)
    savefig("images/$output_filename.png")
end

run_chord_optim(3, 6, 1.0, "tttest3x6")